<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Stock Summary Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 0 auto;
            font-size: 12px;
        }

        header {
            padding: 10px 0;
            text-align: center;
            border-bottom: 1px solid #ccc;
        }

        #logo img {
            width: 100px;
            height: auto;
        }

        h2 {
            margin-top: 10px;
            color: #5D6975;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 30px;
        }

        table th,
        table td {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: center;
        }

        table th {
            background-color: #f2f2f2;
        }

        tfoot td {
            font-weight: bold;
        }

        footer {
            text-align: center;
            margin-top: 50px;
            font-size: 11px;
            border-top: 1px solid #ccc;
            padding-top: 10px;
            color: #888;
        }
    </style>
</head>

<body>

    <header>
        <div id="logo">
            <img src="{{ public_path('Frontend/Assets/Logo.png') }}" alt="Company Logo">
        </div>
        <h2>Stock Summary Report</h2>
        <div>Date: {{ now()->format('d M Y') }}</div>
    </header>

    <main>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Total Purchase Qty</th>
                    <th>Total Sell Qty</th>
                    <th>Stock</th>
                    <th>No of Cartons</th>
                </tr>
            </thead>
            <tbody>
                @php $totalAvailable = 0; @endphp
                @foreach($allProducts as $product)
                    @php $totalAvailable += $product->available_quantity; @endphp
                    <tr>
                        <td style="text-align: left;">{{ $product->name }}</td>
                        <td>{{ $product->total_purchase_qty ?? 0 }}</td>
                        <td>{{ $product->total_sale_qty + $product->total_order_qty }}</td>
                        <td>{{ $product->available_quantity }}</td>
                        <td>
                            @if(!empty($product->no_of_piece_qty_in_carton) && $product->no_of_piece_qty_in_carton != 0)
                                {{ $product->available_quantity / $product->no_of_piece_qty_in_carton }}
                            @else
                                0
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" style="text-align:right;">Total Available Stock</td>
                    <td>{{ $totalAvailable }}</td>
                </tr>
            </tfoot>
        </table>
    </main>

    <footer>
        Report generated by the system — no signature required.
    </footer>

</body>

</html>